version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 559058471915.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`      
      - docker build -t wordpress:5.9.3.tmp1 .
      - docker tag wordpress:5.9.3.tmp1 559058471915.dkr.ecr.us-east-1.amazonaws.com/wordpress:5.9.3.tmp1      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 559058471915.dkr.ecr.us-east-1.amazonaws.com/wordpress:5.9.3.tmp1
